### ISSUE TITLE
RPI aarch64: docker-compose is crashing at start

### ISSUE THREAD

**Issue by mrks1337** [zengxs/gitlab-docker#98]
Hi, I am running the following docker-compose.yml on my Raspberry Pi (aarch64):

```
version: '3.9'

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: "100m"
    max-file: "3"

services:
  gitlab:
    image: zengxs/gitlab:ee-arm64
    container_name: gitlab
    restart: unless-stopped
    ports:
      - "9002:80"
      - "2222:22"
    environment:
      TZ: Europe/Berlin
      GITLAB_OMNIBUS_CONFIG: from_file('/home/pi/gitlab/gitlab.rb')
    volumes:
      # Your gitlab configurations file
      - ./gitlab.rb:/etc/gitlab.rb:ro
      # GitLab data dirs
      - /mnt/sda/gitlab:/etc/gitlab
      - /mnt/sda/gitlab:/var/log/gitlab
      - /mnt/sda/gitlab:/var/opt/gitlab
    logging: *default-logging
```

My gitlab.rb is in the same location as the docker-compose.yml (/home/pi/gitlab):

```
########## GitLab Configurations ##########
# More configurations see: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template

external_url "https://git.somedomain.com"
gitlab_rails['initial_root_password'] = somepass
```

When I check for my container, I only see this:

> pi@raspberry:~/gitlab $ docker container ls | grep gitlab
> 39a8c090bc0b   zengxs/gitlab:ee-arm64                          "/assets/wrapper"        3 minutes ago   Restarting (159) 56 seconds ago                                                                                          > gitlab

Did I miss something to configure?
